### ISSUE TITLE
The baseline of ContEA

### ISSUE THREAD

**Issue by sutaoyu** [nju-websoft/ContEA#6]
Hi,my friends, i want to know how to get results of your baselines(eg:DINGAL-O) in your paper? Could you share the code of baselines about this task? Thank you very much.

**Comment by audreycs** [comment]
Hello, sorry for the super late reply. Our implementation of DINGAL-O is available here: https://www.dropbox.com/scl/fo/sl1jweiqycwr4d7zhu3ud/AIklr3Ec5RYnkBp-Zx86UeU?rlkey=sqp0mtun1hi9oji22co90og5m&st=wyx1os81&dl=0
